version: '2'
services:
 app:
  image: busybox
  container_name: "app"
  volumes:
   - ../www:/var/www
  networks:
    vpcbr:
      ipv4_address: 10.2.0.2

 mysql:
  image: reflet/debian8-mysql57:1.1
  container_name: 'mysql'
  env_file: .env.mysql
  ports:
   - '3306:3306'
  volumes:
   - ./.initdb.mysql:/docker-entrypoint-initdb.d/
  networks:
    vpcbr:
      ipv4_address: 10.2.0.3

 postgres:
  image: reflet/debian8-postgres96:1.1
  container_name: 'postgres'
  env_file: .env.postgres
  ports:
   - "5432:5432"
  volumes:
   - ./initdb.postgres:/docker-entrypoint-initdb.d/
  networks:
    vpcbr:
      ipv4_address: 10.2.0.4

 php:
  image: reflet/debian8-php71:1.1
  container_name: "php"
  ports:
   - '9000:9000'
  volumes:
   - ./php.ini:/usr/local/etc/php/php.ini
   - ./php-ssmtp.conf:/etc/ssmtp/ssmtp.conf
  volumes_from:
   - app
  extra_hosts:
   - "www.example.com:10.2.0.6"
  networks:
    vpcbr:
      ipv4_address: 10.2.0.5

 httpd:
  image: reflet/debian8-httpd:1.6
  container_name: "httpd"
  ports:
   - '80:80'
   - '443:443'
  volumes:
   - ./virtualhost:/usr/local/apache2/conf.d/virtualhost/
   - httpd-log:/usr/local/apache2/logs/
  volumes_from:
   - app
  networks:
    vpcbr:
      ipv4_address: 10.2.0.6

 selenium:
  image: selenium/standalone-chrome-debug:latest
  container_name: "selenium"
  ports:
   - '4444:4444'
   - '5900:5900'

volumes:
  postgres-data:
    driver: local
  mysql-data:
    driver: local
  httpd-log:
    driver_opts:
      type: none
      device: /home/vagrant/opt/docker/logs/httpd/
      o: bind

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.2.0.0/16
         gateway: 10.2.0.1

