version: '2'
services:
 app:
  image: busybox
  container_name: "app"
  volumes:
   - ../www:/var/www
   - ./logs/httpd:/usr/local/apache2/logs
   - ./data/mysql:/var/lib/mysql
   - ./data/postgres:/var/lib/postgresql

 mysql:
  image: reflet/debian8-mysql57:1.1
  container_name: 'mysql'
  env_file: .env.mysql
  ports:
   - '3306:3306'
  volumes:
   - ./.initdb.mysql:/docker-entrypoint-initdb.d/
  volumes_from:
   - app

 postgres:
  image: reflet/debian8-postgres96:1.0
  container_name: 'postgres'
  env_file: .env.postgres
  volumes:
      - ./initdb.postgres:/docker-entrypoint-initdb.d/
  ports:
      - "5432:5432"
  volumes_from:
      - app

 php:
  image: reflet/debian8-php71:1.1
  container_name: "php"
  ports:
   - '9000:9000'
  volumes:
   - ./php.ini:/usr/local/etc/php/php.ini
  volumes_from:
   - app
  links:
   - mysql
   - postgres

 httpd:
  image: reflet/debian8-httpd:1.6
  container_name: "httpd"
  ports:
   - '80:80'
   - '443:443'
  volumes:
   - ./virtualhost:/usr/local/apache2/conf.d/virtualhost/
  volumes_from:
   - app
  links:
   - php

